### ISSUE TITLE
`SmartString::deref` panics

### ISSUE THREAD

**Issue by ritchie46** [bodil/smartstring#40]
I am still investigating further, but after upgrading to latest nightly compiler, I get a panic with `smartstring`.

Here is the backtrace:

```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'range end index 52 out of range for slice of length 23', /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smartstring-1.0.1/src/inline.rs:43:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/panicking.rs:67:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/slice/index.rs:78:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/slice/index.rs:70:9
   4: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/slice/index.rs:411:13
   5: <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/slice/index.rs:458:9
   6: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/slice/index.rs:19:9
   7: core::array::<impl core::ops::index::Index<I> for [T; N]>::index
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/array/mod.rs:348:9
   8: <smartstring::inline::InlineString as core::ops::deref::Deref>::deref
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smartstring-1.0.1/src/inline.rs:43:34
   9: <smartstring::SmartString<Mode> as core::ops::deref::Deref>::deref
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smartstring-1.0.1/src/lib.rs:227:43
  10: <smartstring::SmartString<Mode> as core::convert::AsRef<str>>::as_ref
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smartstring-1.0.1/src/lib.rs:540:14
  11: <&T as core::convert::AsRef<U>>::as_ref
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/convert/mod.rs:668:9
  12: polars_core::chunked_array::builder::utf8::Utf8ChunkedBuilder::append_value
             at /home/ritchie46/code/polars/polars/polars-core/src/chunked_array/builder/utf8.rs:28:32
  13: polars_core::frame::row::av_buffer::AnyValueBufferTrusted::add_unchecked_owned_physical
             at /home/ritchie46/code/polars/polars/polars-core/src/frame/row/av_buffer.rs:428:25
  14: polars_pipe::executors::sinks::groupby::generic2::hash_table::AggHashTable<_>::finalize::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic2/hash_table.rs:320:25
  15: <core::iter::adapters::take::Take<I> as core::iter::traits::iterator::Iterator>::for_each::check::{{closure}}
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/iter/adapters/take.rs:112:17
  16: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/iter/traits/iterator.rs:2305:21
  17: <core::iter::adapters::skip::Skip<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/iter/adapters/skip.rs:113:9
  18: <core::iter::adapters::take::Take<I> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/iter/adapters/take.rs:119:13
  19: polars_pipe::executors::sinks::groupby::generic2::hash_table::AggHashTable<_>::finalize
             at /home/ritchie46/code/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic2/hash_table.rs:304:9
  20: polars_pipe::executors::sinks::groupby::generic2::global::GlobalTable::finalize::{{closure}}::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic2/global.rs:164:25
  21: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/ops/function.rs:274:13
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/ops/function.rs:310:13
  23: core::option::Option<T>::map
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/option.rs:1099:29
  24: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/iter/adapters/map.rs:103:9
  25: rayon::iter::plumbing::Folder::consume_iter
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:178:21
  26: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/map.rs:248:21
  27: rayon::iter::plumbing::Producer::fold_with
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
  28: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  29: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:427:21
  30: rayon_core::join::join_context::call_b::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:129:25
  31: rayon_core::job::JobResult<T>::call::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:218:41
  32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/core/src/panic/unwind_safe.rs:271:9
  33: std::panicking::try::do_call
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/std/src/panicking.rs:485:40
  34: std::panicking::try
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/std/src/panicking.rs:449:19
  35: std::panic::catch_unwind
             at /rustc/88fb1b922b047981fc0cfc62aa1418b4361ae72e/library/std/src/panic.rs:140:14
  36: rayon_core::unwind::halt_unwinding
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  37: rayon_core::job::JobResult<T>::call
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:218:15
  38: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:120:32
  39: rayon_core::job::JobRef::execute
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:64:9
  40: rayon_core::registry::WorkerThread::execute
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:874:13
  41: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:820:22
  42: rayon_core::registry::WorkerThread::wait_until
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:803:13
  43: rayon_core::registry::main_loop
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:948:5
  44: rayon_core::registry::ThreadBuilder::run
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:54:18
  45: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/ritchie46/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:99:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by ritchie46** [comment]
I will close for now, until I ruled out everything on my side.
